import React from "react";
import { 
  FileCode, 
  Terminal, 
  Github, 
  Copy, 
  ChevronRight, 
  ShieldCheck,
  Zap,
  Globe,
  Database
} from "lucide-react";

export default function ApiDocs() {
  const sections = [
    {
      title: "Network API Architecture",
      icon: Terminal,
      description: "Direct server-to-server (S2S) communication protocols for programmatic campaign management and attribution signaling.",
      endpoints: [
        {
          method: "GET",
          path: "/api/track/click",
          params: [
            { name: "cmp", type: "UUID", desc: "Campaign Unique Identifier" },
            { name: "aff", type: "UUID", desc: "Affiliate/Publisher Identifier" }
          ],
          desc: "Primary traffic ingestion node. Performs geo-targeting, device detection, and capping validation before redirection."
        },
        {
          method: "GET",
          path: "/api/track/postback",
          params: [
            { name: "click_id", type: "UUID", desc: "Original session ID from click" },
            { name: "rev", type: "Decimal", desc: "Total revenue generated by the event" }
          ],
          desc: "S2S Postback signal. Calculates payout based on revenue-share logic or flat-fee overrides."
        }
      ]
    },
    {
      title: "Publisher API Suite",
      icon: Globe,
      description: "Endpoints exposed for third-party affiliate systems to fetch real-time creative assets and link generators.",
      endpoints: [
        {
          method: "GET",
          path: "/api/publisher/offers",
          params: [{ name: "key", type: "String", desc: "Publisher API Secret" }],
          desc: "Retrieves active campaigns with valid creative payloads."
        }
      ]
    }
  ];

  return (
    <div className="space-y-8 max-w-6xl mx-auto pb-20">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-[#1e293b] flex items-center">
            <FileCode className="w-8 h-8 mr-3 text-[#1ea4d9]" /> APIDocs & SDKs
          </h2>
          <p className="text-[#64748b] mt-1">Industrial-grade protocols for the AdMagic high-frequency tracking cluster.</p>
        </div>
        <div className="flex space-x-3">
          <button className="flex items-center space-x-2 px-4 py-2 bg-[#1e293b] text-white rounded-lg text-sm font-bold hover:bg-black transition-all">
            <Github className="w-4 h-4" />
            <span>View Repositories</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        <div className="lg:col-span-3 space-y-8">
          {sections.map((section, idx) => (
            <div key={idx} className="panel space-y-6">
              <div className="flex items-center space-x-3 border-b border-[#f1f5f9] pb-4">
                <div className="p-2 bg-[#f0f9ff] rounded-lg">
                  <section.icon className="w-5 h-5 text-[#1ea4d9]" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-[#1e293b]">{section.title}</h3>
                  <p className="text-xs text-[#64748b]">{section.description}</p>
                </div>
              </div>

              <div className="space-y-8">
                {section.endpoints.map((ep, eIdx) => (
                  <div key={eIdx} className="space-y-4">
                    <div className="flex items-center space-x-3">
                      <span className={`px-2 py-1 rounded text-[10px] font-bold ${
                        ep.method === 'GET' ? 'bg-blue-100 text-blue-700' : 'bg-emerald-100 text-emerald-700'
                      }`}>
                        {ep.method}
                      </span>
                      <code className="text-sm font-mono text-[#1e293b] bg-[#f8fafc] px-2 py-1 rounded border border-[#e2e8f0]">
                        {ep.path}
                      </code>
                    </div>
                    <p className="text-sm text-[#475569] leading-relaxed pl-2 border-l-2 border-[#1ea4d9]/10">
                      {ep.desc}
                    </p>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 ml-2">
                      {ep.params.map((p, pIdx) => (
                        <div key={pIdx} className="flex items-center justify-between p-3 bg-[#f8fafc] border border-[#e2e8f0] rounded">
                          <div>
                            <span className="text-xs font-mono font-bold text-[#1ea4d9]">{p.name}</span>
                            <span className="mx-2 text-[#94a3b8]">|</span>
                            <span className="text-[10px] text-[#64748b] uppercase tracking-widest">{p.type}</span>
                          </div>
                          <span className="text-[10px] text-[#94a3b8] italic">{p.desc}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="space-y-6">
          <div className="panel bg-[#1e293b] text-white">
            <h4 className="font-bold text-sm mb-4 flex items-center">
              <ShieldCheck className="w-4 h-4 mr-2 text-[#BFFF00]" /> Auth Protocol
            </h4>
            <div className="space-y-4 text-xs">
              <p className="text-[#94a3b8] leading-relaxed">
                All programmatic requests must include the <code className="text-[#BFFF00]">X-API-KEY</code> header derived from your security settings.
              </p>
              <div className="p-3 bg-black/20 rounded border border-white/5 font-mono">
                X-API-KEY: key_live_...
              </div>
            </div>
          </div>

          <div className="panel space-y-4">
            <h4 className="font-bold text-sm text-[#1e293b] flex items-center">
              <Zap className="w-4 h-4 mr-2 text-[#1ea4d9]" /> Automation Setup
            </h4>
            <div className="space-y-3">
              {[
                "Webhooks & Callbacks",
                "Bulk URL Export",
                "Inventory Sync",
                "Bot Detection Engine"
              ].map(item => (
                <div key={item} className="flex items-center text-xs text-[#64748b] group cursor-pointer hover:text-[#1ea4d9]">
                  <ChevronRight className="w-3 h-3 mr-2 opacity-60 group-hover:translate-x-1 transition-all" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="panel bg-gradient-to-br from-[#1ea4d9] to-[#0ea5e9] text-white p-6 shadow-xl relative overflow-hidden">
            <Database className="w-16 h-16 absolute -bottom-4 -right-4 opacity-10" />
            <h4 className="font-bold text-lg mb-2">Integration SDK</h4>
            <p className="text-xs opacity-90 mb-4 font-medium leading-relaxed">Download our pre-built Node.js, Python, and Go handlers for localized event processing.</p>
            <button className="w-full py-2 bg-white text-[#1ea4d9] rounded font-bold text-xs hover:shadow-lg transition-all">
              DOWNLOAD SDK
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
